RonasIT/laravel-helpers

src/Traits/ModelTrait.php

- fixed types in scopeOrderByRelated method;

Fixed bug with scopeOrderByRelated method in Laravel 8

---

documentation/helpers.md
documentation/migration.md
documentation/services.md
documentation/traits.md
src/BaseRequest.php
src/Exporters/Exporter.php
src/HelpersServiceProvider.php
src/Importers/Importer.php
src/Interfaces/DataCollectorInterface.php
src/Interfaces/ExporterInterface.php
src/Iterators/DBIterator.php
src/Middleware/AuthWithRefresh.php
src/Middleware/SecurityMiddleware.php
src/Middleware/UndemandingAuthorizationMiddleware.php
src/Services/HttpRequestService.php
src/Stubs/add_default_user.blade.php
src/Traits/EntityControlTrait.php
src/Traits/FilesTestTrait.php
src/Traits/FilesTrait.php
src/Traits/FilesUploadTrait.php
src/Traits/FixturesTrait.php
src/Traits/ImageTestTrait.php
src/Traits/ImagesTrait.php
src/Traits/MigrationTrait.php
src/Traits/MockHttpRequestTrait.php
src/Traits/ModelTrait.php
src/Traits/SearchTrait.php
src/helpers.php
tests/HelpersTest.php
tests/TestCase.php

feat: implement is_multidimensional helper, update docs
refs: #33

fix: updateMany use undefined variable;

---

src/Traits/SearchTrait.php

#65:- optimize search

---

src/Traits/SearchTrait.php

#44:- adding missing reserved filters;

---

src/Traits/SearchTrait.php

#44:- fix: fix reserved filters

---

tests/TestCase.php

feat: add the ability to test the From field for email

feat: add the ability to test the From field for email

---

src/Exceptions/InvalidJSONFormatException.php
src/Services/HttpRequestService.php

fix: call json method with non json response

---

src/HelpersServiceProvider.php
tests/ValidatorTest.php
tests/support/Traits/SqlMockTrait.php

fix: unique_except_of_authorized_user fails when value is array

---

src/Traits/SearchTrait.php
tests/SearchTraitTest.php
tests/support/Traits/SqlMockTrait.php

- Unnecessary text conversion was removed
- Mask for query filter was added (useful in multilingual texts)

Remove unnecessary text convertion

---

Dockerfile
src/Traits/FixturesTrait.php
tests/fixtures/FixturesTraitTest/prepare_sequences/sequences.sql

refs: 
https://app.clickup.com/t/862kbnxxa

Fix prepare sequence

---

.gitignore
.php-cs-fixer.dist.php
composer.json
composer.lock
src/HelpersServiceProvider.php
src/Services/HttpRequestService.php

We have the following warning 
```sh
Implicit conversion from float 1721702613.39006 to int loses precision in /app/vendor/ronasit/laravel-helpers/src/Services/HttpRequestService.php on line 187
```

Fix warning with logging

---

src/HelpersServiceProvider.php

Done:
- switch DB connection in service provider when tests are running in parallel;

feat: set up project to use Paratest;

---

src/Traits/MockTrait.php
tests/FixturesTraitTest.php
tests/MockTraitTest.php

https://github.com/RonasIT/laravel-helpers/issues/145

#145: Mock class not assert arguments with the empty arg list

---

src/Traits/MockTrait.php
tests/MockTraitTest.php

https://github.com/RonasIT/laravel-helpers/issues/145#issuecomment-2534352900

#145: Fix bug with empty arguments

---

src/BaseRequest.php
tests/BaseRequestTest.php

https://github.com/RonasIT/laravel-helpers/issues/161

#161: Ability to validate order_by field

---

src/BaseResource.php

https://github.com/RonasIT/laravel-helpers/issues/167

#167: Implement BaseResource class

---

src/Traits/EntityControlTrait.php
tests/EntityControlTraitTest.php
tests/support/Mock/TestModelWithDifferentTimestampNames.php
tests/support/Mock/TestModelWithoutTimestamps.php
tests/support/Mock/TestRepositoryWithDifferentTimestampNames.php
tests/support/Mock/TestRepositoryWithoutTimestamps.php
tests/support/Traits/SqlMockTrait.php

https://github.com/RonasIT/laravel-helpers/issues/165

#165: Implement insert method

---

.gitignore
src/Traits/FixturesTrait.php
tests/FixturesTraitTest.php

https://github.com/RonasIT/laravel-helpers/issues/166

#166: auto add json extension

---

src/HelpersServiceProvider.php

https://github.com/RonasIT/laravel-helpers/issues/77#issuecomment-2581848578

fix: refactor list_exists error message

---

src/HelpersServiceProvider.php
tests/ValidatorTest.php

https://github.com/RonasIT/laravel-helpers/issues/77#issuecomment-2589042352

fix: add array check in list_exists rule

---

tests/TestCase.php

https://github.com/RonasIT/laravel-helpers/issues/185

#185: change setUp method visibility

---

composer.json
composer.lock

#191: remove tecnickcom/tcpdf; update dependencies

---

composer.json
composer.lock

#191: remove tecnickcom/tcpdf

---

.gitattributes

refs: https://github.com/RonasIT/laravel-helpers/issues/189

feat: create .gitattributes file

---

src/Http/Middleware/CheckIpMiddleware.php
tests/CheckIpMiddlewareTest.php

refs: https://github.com/RonasIT/laravel-helpers/issues/214

feat: Implement middleware to restrict IP access

---

src/Http/Middleware/CheckIpMiddleware.php
tests/CheckIpMiddlewareTest.php

refs: https://github.com/RonasIT/laravel-telescope-extension/issues/30

feat: add $request->ips() to current ip
